sudo: false

dist: trusty

language: php

php:
#  - 5.6
#  - 7.0
#  - 7.1
  - 7.2
#  - 7.3
#  - 7.4

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction -o

script: ./vendor/bin/phpunit --debug
