sudo: false

dist: trusty

language: php

php:
  - 5.4
  - 7.0
  - 7.1

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction

script: cd tests/suites/ && php all.php
